databases:
  - name: evercare-garage-db
    databaseName: evercare_garage
    user: evercare_garage

services:
  - type: web
    name: evercare-garage
    runtime: python
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --no-input && python manage.py migrate
    startCommand: gunicorn config.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: CSRF_TRUSTED_ORIGINS
        value: "https://*.onrender.com"
      - key: DATABASE_URL
        fromDatabase:
          name: evercare-garage-db
          property: connectionString
      - key: SECURE_SSL_REDIRECT
        value: "True"
      - key: SECURE_HSTS_SECONDS
        value: "31536000"
      - key: SECURE_HSTS_INCLUDE_SUBDOMAINS
        value: "True"
      - key: SECURE_HSTS_PRELOAD
        value: "True"
