# Generated by Django 6.0.4 on 2026-09-02 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='handled',
            field=models.BooleanField(default=False),
        ),
    ]
