# Generated by Django 6.0.4 on 2026-09-02 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0002_contactmessage_handled'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='custom_service',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
